Item listing
koukiokumura/mercari pull request #7
Opened 2019-03-11 09:57 UTC by koukiokumura

##WHTA
商品出品機能の実装
##WHY
ユーザーが商品を売れるようにするため

2019-03-11 10:36 UTC, ghost requested changes
.

2019-03-11 10:36 UTC, hiroki5123 commented on app/assets/javascripts/item_new.js
> +  var target = document.getElementById('drop');
$("#drop")
で取得できませんか？

2019-03-11 10:36 UTC, hiroki5123 commented on app/assets/javascripts/item_new.js
> +  var select_large = $('.large-category')
;が必要です。

2019-03-11 11:23 UTC, koukiokumura commented on app/assets/javascripts/item_new.js
> +  var target = document.getElementById('drop');
試してみましたがドロップできませんでした。

2019-03-11 11:23 UTC, koukiokumura commented on app/assets/javascripts/item_new.js
> +  var select_large = $('.large-category')
訂正しました。

2019-03-12 04:36 UTC, katoShiro46 commented on app/models/item.rb
> +  SHIPPING_DATE = ["1~2日で発送","2~3日で発送","4~7日で発送"]
Itemテーブルに重複する多数のString型のレコード値が保存されることになるので、Condition,Shipping_fee,Shipping_method,Shipping_dateはactivehash、もしくはDB上でテーブル持たせて、Itemテーブルのレコードはinteger型で保存されるべき。
けど、時間ないから今のまま、String型でDBに保存する形で行っちゃいましょう。

2019-03-12 04:36 UTC, katoShiro46 commented on app/controllers/items_controller.rb
> +  end
9行目
中カテゴリーを
Category.where(category.depth:1)とかでカテゴリーとかで呼び出せないのだっけ？

2019-03-12 08:33 UTC, ghost requested changes

2019-03-12 08:33 UTC, hiroki5123 commented on app/models/item.rb
>    CONDITION = ["新品、未使用","未使用に近い","目立った傷や汚れなし","やや傷や汚れあり","傷や汚れあり","全体的に状態が悪い"]
enumとか使わないんでしょうか・・・？

2019-03-12 11:49 UTC, koukiokumura commented on app/models/item.rb
>    CONDITION = ["新品、未使用","未使用に近い","目立った傷や汚れなし","やや傷や汚れあり","傷や汚れあり","全体的に状態が悪い"]
enumを使った記述に変更しました。

2019-03-12 11:56 UTC, ghost approved these changes
LGTMです。

2019-03-12 15:27 UTC, merged